version: "3.8"

services:
  app:
    build:
      context: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      rollback_config:
        parallelism: 1
    volumes:
      - vectorDB:/app/vectorDB
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always

volumes:
  vectorDB:
